name: Aldor
slogan: Programming Language
markdown: redcarpet
pygments: true

menus:
   main:
      - 'Home': /
      - 'Using Aldor':
         - /users
         - 'Community wiki': https://github.com/pippijn/aldor/wiki
         - 'Aldor User Guide': http://www.aldor.org/docs/aldorug.pdf
      - 'Development':
         - /devel
         - 'Try Aldor': /eval
         - 'Source repository': https://github.com/pippijn/aldor
         - 'Mailing list': https://groups.google.com/forum/#!forum/aldor-devel
